### ISSUE TITLE
Question(builders): Versioning runs for every Project

### ISSUE THREAD

**Issue by johannesschobel** [ng-easy/platform#612]
Dear @samuelfernandez ,

i ran into the problem, that the `versioning process` via your `semver` library runs for every library, even if this respective library does not have any commits affecting them.

This leads to my question, how the library detects, if one commit affects one particular library. Initially, i thought, that the files within the commit are analyzed, but that cannot be true.

I guess, it is the commit message format, right?

My latest commit message look as follows:

* fix: get rid of logger
* feat: migrate to prisma 4
* fix: release script
* chore: update deps

and stuff like this.

Do i need to specifically target a project this commit belongs to? Like so:

* fix(nestjs-prisma): get rid of logger
* feat(nestjs-prisma): migrate to prisma 4

In this case, only `nestjs-prisma` lib would get updated, but the others will not?

All the best and thanks for clarifying this issue
Johannes

**Comment by samuelfernandez** [comment]
@johannesschobel there is no ase automatic process of detecting the affected project based on touched files. The way it works is by detecting the conventional commit name, and matching the commit name with the project name. In the documentation for the builder there is an example. This brings you full control on the version that will be applied to each project by controlling the scope.

In your first example, since there is no scope those changes will affect all projects. I hope this further clarifies your question!

**Comment by johannesschobel** [comment]
see #613
